# Due to rate limiting from digikey.com and gnu.org
accept = [429]

cache = true
exclude = [
  # Raspberry Pi's website returns 403 forbidden codes for GitHub runners.
  '^https://www.raspberrypi.com',
  # https://opensource.org returns 403 forbidden codes for GitHub runners.
  '^https://opensource.org',
]
exclude_path = [".direnv/", "result/", "target/"]
max_cache_age = "2w"
