name: Cargo Lock Updater

"on":
  schedule:
    # Once a month on the 5th
    - cron: "0 0 5 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  cargo-lock-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - name: Update ATtiny85 Cargo lock file
        run: nix develop .#attiny85 --command 'cd boards/attiny85 && cargo update'
      - name: Update Pico Cargo lock file
        run: nix develop .#pico --command 'cd boards/pico && cargo update'
      - name: Update QT Py CH32V203 Cargo lock file
        run: nix develop .#qt-py-ch32v203 --command 'cd boards/qt-py-ch32v203 && cargo update'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          assignees: ${{ github.repository_owner }}
          branch: "update/cargo-lock"
          commit-message: "chore(deps): Update Cargo lock files"
          title: "chore(deps): Update Cargo lock files"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
