name: Lint Rust code with Clippy
"on":
  pull_request:
    branches: ["main"]
    paths:
      - '*.nix'
      - .github/workflows/clippy-attiny85.yaml
      - .justfile
      - boards/attiny85/.cargo/**
      - boards/attiny85/avr-unknown-none-attiny85.json
      - boards/attiny85/Cargo.lock
      - boards/attiny85/Cargo.toml
      - boards/attiny85/**.nix
      - boards/attiny85/rust-toolchain.toml
      - boards/attiny85/src/**
      - flake.lock
  push:
    branches: ["main"]
    paths:
      - '*.nix'
      - .github/workflows/clippy-attiny85.yaml
      - .justfile
      - boards/attiny85/.cargo/**
      - boards/attiny85/avr-unknown-none-attiny85.json
      - boards/attiny85/Cargo.lock
      - boards/attiny85/Cargo.toml
      - boards/attiny85/**.nix
      - boards/attiny85/rust-toolchain.toml
      - boards/attiny85/src/**
      - flake.lock

jobs:
  clippy-attiny85:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
